######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 6 20:37:25 2010
######################################################################

CONFIG+=qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testKernels.h
SOURCES += testKernels.cpp
